pipeline {
    agent any 

    tools { 
        maven 'Maven 3.3.6' 
        jdk 'jdk8' 
    }
    
    stages {   
        stage('Unit Test') { 
            steps {
		    sh "mvn test -f griffinApp -pl -griffinApp-IntegrationTest"
            }
        }
        stage('Integration Test') { 
            steps {
	     //sh  "mvn test -Pintegration-tests -Djboss.home=/opt/wildfly-8.2.1.Final -f griffinApp"
	      echo 'This is integration test'
            }
        }
        stage('Build') { 
            steps {
		sh "mvn clean install -f griffinApp"
            }
        }
        stage ('Static Code Analysis') {
            steps {
             sh "mvn pmd:pmd -f griffinApp -pl -griffinApp-IntegrationTest"
            }
        } 
        stage('Findbugs Analysis'){
            steps{
            sh "mvn findbugs:findbugs -f griffinApp"
            }
        }

    }
    
    post {  
         always {  
            echo 'This action mines the repository for commit forensics'  
            mineRepository()
	        junit allowEmptyResults: true, testResults: 'griffinApp/griffinApp-JarModule/target/surefire-reports/*.xml'
	        junit allowEmptyResults: true, testResults: 'griffinApp/griffinApp-WarModule/target/surefire-reports/*.xml'
		recordIssues enabledForFailure: true, sourceCodeEncoding: 'UTF-8', tools: [pmdParser()]
		recordIssues enabledForFailure: true, tools: [findBugs(useRankAsPriority: true)]
	    	jacoco exclusionPattern: '**/*Test*.class', inclusionPattern: '**/*.class', runAlways: true    
         }  
         success {  
	    archiveArtifacts artifacts: 'griffinApp/griffinApp-JarModule/target/*.jar', followSymlinks: false     
	    archiveArtifacts artifacts: 'griffinApp/griffinApp-WarModule/target/*.war', followSymlinks: false         
	    archiveArtifacts artifacts: 'griffinApp/griffinApp-EarModule/target/*.ear', followSymlinks: false         
    
	 }  

     }      
}