pipeline {
    agent any 

    tools { 
        maven 'Maven 3.3.6' 
        jdk 'jdk8' 
    }
    
    stages {
	stage ('Static Code Analysis') {
            steps {
	     sh "mvn clean -f griffinApp"
             sh "mvn pmd:pmd -f griffinApp"
             sh "mvn checkstyle:checkstyle -f griffinApp"
            }
        }    
        stage('Unit Test') { 
            steps {
		sh "mvn test -f griffinApp"
            }
        }
        stage('Integration Test') { 
            steps {
	        echo "This is the integration test stage"
		// sh "mvn test -Parquillian-test -f griffinApp"
            }
        }
        stage('Build') { 
            steps {
		sh "mvn install -f griffinApp"
            }
        }
        stage('Findbugs Analysis'){
            steps{
            sh "mvn findbugs:findbugs -f griffinApp"
            }
        }

    }
    
    post {  
         always {  
            echo 'This action mines the repository for commit forensics'  
            mineRepository()
	        junit allowEmptyResults: true, testResults: 'griffinApp/griffinApp-JarModule/target/surefire-reports/*.xml'
	        junit allowEmptyResults: true, testResults: 'griffinApp/griffinApp-WarModule/target/surefire-reports/*.xml'
	        recordIssues enabledForFailure: true, sourceCodeEncoding: 'UTF-8', tools: [pmdParser()]
            recordIssues enabledForFailure: true, tools: [checkStyle()] 
            recordIssues enabledForFailure: true, tools: [findBugs(useRankAsPriority: true)]
	    jacoco exclusionPattern: '**/*Test*.class', inclusionPattern: '**/*.class', runAlways: true    
         }  
         success {  
	    archiveArtifacts artifacts: 'griffinApp/griffinApp-JarModule/target/*.jar', followSymlinks: false     
	    archiveArtifacts artifacts: 'griffinApp/griffinApp-WarModule/target/*.war', followSymlinks: false         
	    archiveArtifacts artifacts: 'griffinApp/griffinApp-EarModule/target/*.ear', followSymlinks: false         
    
	 }  

     }      
}
